// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class WelcomeChannel extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.WelcomeChannel";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.WelcomeChannel";
    }

    public com.duowan.gamenews.Channel channel = null;

    public boolean isSelected = true;

    public String iconPath = "";

    public boolean fromServer = true;

    public com.duowan.gamenews.Channel getChannel()
    {
        return channel;
    }

    public void  setChannel(com.duowan.gamenews.Channel channel)
    {
        this.channel = channel;
    }

    public boolean getIsSelected()
    {
        return isSelected;
    }

    public void  setIsSelected(boolean isSelected)
    {
        this.isSelected = isSelected;
    }

    public String getIconPath()
    {
        return iconPath;
    }

    public void  setIconPath(String iconPath)
    {
        this.iconPath = iconPath;
    }

    public boolean getFromServer()
    {
        return fromServer;
    }

    public void  setFromServer(boolean fromServer)
    {
        this.fromServer = fromServer;
    }

    public WelcomeChannel()
    {
        setChannel(channel);
        setIsSelected(isSelected);
        setIconPath(iconPath);
        setFromServer(fromServer);
    }

    public WelcomeChannel(com.duowan.gamenews.Channel channel, boolean isSelected, String iconPath, boolean fromServer)
    {
        setChannel(channel);
        setIsSelected(isSelected);
        setIconPath(iconPath);
        setFromServer(fromServer);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        WelcomeChannel t = (WelcomeChannel) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(channel, t.channel) && 
            com.duowan.taf.jce.JceUtil.equals(isSelected, t.isSelected) && 
            com.duowan.taf.jce.JceUtil.equals(iconPath, t.iconPath) && 
            com.duowan.taf.jce.JceUtil.equals(fromServer, t.fromServer) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != channel)
        {
            _os.write(channel, 0);
        }
        _os.write(isSelected, 1);
        if (null != iconPath)
        {
            _os.write(iconPath, 2);
        }
        _os.write(fromServer, 3);
    }

    static com.duowan.gamenews.Channel cache_channel;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_channel)
        {
            cache_channel = new com.duowan.gamenews.Channel();
        }
        setChannel((com.duowan.gamenews.Channel) _is.read(cache_channel, 0, false));

        setIsSelected((boolean) _is.read(isSelected, 1, false));

        setIconPath( _is.readString(2, false));

        setFromServer((boolean) _is.read(fromServer, 3, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(channel, "channel");
        _ds.display(isSelected, "isSelected");
        _ds.display(iconPath, "iconPath");
        _ds.display(fromServer, "fromServer");
    }

}

